model_config:
  execution_mode: moe
  d_model: 768
  n_repeats: 6
  n_heads: 3
  n_experts_ffn: 192
  n_experts_attn: 10
  d_head: 128
  k_ffn: 12
  k_attn: 2
  d_expert_ffn: 128
  n_layers: 2
  vocab_size: 50368
  max_seq_len: 1024
  n_expert_shared_attn: 0
  n_expert_shared_ffn: 0
  collect_reg_loss: False
  enable_early_exit: False
  norm_structure: "peri"
  rescaling_method: "avg_prot_emb"

train:
  max_duration: "3171ba"
  warmup: "634ba"
  cooldown: "634ba"
  device_train_batch_size: 1024

callbacks:
  lr_monitor: {}
  clean_metrics:
    interval: 100
  speed_monitor:
    window_size: 10
    gpu_flops_available:
        fp64: 67e12,
        fp32: 67e12,
        tf32: 989e12 / 2,
        fp16: 1.979e15 / 2,
        amp_fp16: 1.979e15 / 2,
        bf16: 1.979e15 / 2,
        amp_bf16: 1.979e15 / 2,
        fp8: 3.958e15 / 2,
        amp_fp8: 3.958e15 / 2,
        int8: 3.958e15 / 2,
  memory_monitor: {}
  runtime_estimator: {}
  optimizer_monitor: {}
  expert_selection_callback:
    attn_experts: ${model_config.n_experts_attn}
    ffn_experts: ${model_config.n_experts_ffn}
    log_interval: 100
  entropy_callback:
    log_interval: 100
  residual_magnitude:
    log_interval: 100
  # layer_usage_monitor:
  #   log_interval: 20
  # # # activation_monitor_c: {}

data_config:
  path: "/nfs-share/pa511/code_bases/dyna_project/dyna/configuration/streams"
  dataset:
    max_seq_len: ${model_config.max_seq_len}
  num_workers: 24
  pin_memory: false

  

trainer_config:
  run_name: "avg"
  max_duration: ${train.max_duration}
  train_dataloader_label: "train"
  device_train_microbatch_size: auto
  precision: "amp_fp16"
  device: "gpu"
  save_folder: "s3://loop-llm/dyna/"
  save_interval: "100ba"
  parallelism_config:
    pipeline_parallel_size: null
    tensor_parallel_size: null

scheduler_config:
  name: "wsld"
  t_warmup: ${train.warmup}
  t_max: ${train.max_duration}
  t_cooldown: ${train.cooldown}
  alpha_f: 1.0


optimizer_config:
  name: "decoupled_adamw"
  lr: 0.0014
  weight_decay: 0.01
  betas: [0.9, 0.95]
  eps: 1e-8